# NumPy Exercises - Solutions

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### windows 
#### python -m pip install numpy pandas matplotlib seaborn plotly ipykernel
#### python -m ipykernel install --user

#### Ubuntu
#### sudo apt-get install python-pip  
#### sudo pip install numpy pandas matplotlib seaborn plotly ipykernel

In [45]:
import numpy as np

#### Create an array of 10 zeros 

In [46]:
np.zeros(10,dtype= 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [47]:
np.ones(10,dtype= 'int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [48]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [49]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [50]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [51]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

#### Create a 3x3 identity matrix

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [53]:
np.random.rand(10)

array([0.04019298, 0.38745674, 0.45045896, 0.42821255, 0.43879128,
       0.09348506, 0.19469189, 0.7717013 , 0.20699026, 0.76383574])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [54]:
np.random.randn(25)

array([-1.6234183 ,  1.10842072,  0.70363387,  0.82187834, -1.23704689,
        0.48708018,  0.66624552,  0.46874562, -1.3702359 ,  0.92929006,
        1.06504847, -1.39880244, -0.77104265, -0.15518851,  2.40180593,
        0.96812695, -0.07971095, -0.73672159,  0.30950169,  0.35362933,
        1.16073024,  0.25129755,  1.06637991, -1.12774279,  1.09605309])

#### Create the following matrix:

In [55]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [56]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [57]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [59]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [60]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [61]:
mat[3,4]

20

In [62]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [63]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [64]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [65]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [66]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [67]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [68]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [69]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [70]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
mat.sum(axis =0)

array([55, 60, 65, 70, 75])

In [72]:
mat.max(axis = 0)

array([21, 22, 23, 24, 25])

In [73]:
mat2 =  np.arange(1,37,1).reshape(6,6)
mat2.shape


(6, 6)

In [74]:
temp = np.array([1,2,3,1,2,3,1,2,3]).reshape(3,3)
b_filt = temp>=2
temp[b_filt]

array([2, 3, 2, 3, 2, 3])

In [75]:
print("Hello world")

Hello world


In [79]:
import pandas as pd
dict = [{"name" : "Gaurav" , "rollno" : 's1' , "salary" : 1000 , "dept" : "comp"},
        {"name" : "Pratik" , "rollno" : 's2' , "salary" : 700,"dept" : "IT"},
        {"name" : "Sneha" , "rollno" : 's3' , "salary" : 600,"dept" : "comp"},
       {"name" : "Mayur" , "rollno" : 's4' , "salary" : 500,"dept" : "Mech"}
       ]

df = pd.DataFrame(dict) 

df

name rollno  salary  dept
0  Gaurav     s1    1000  comp
1  Pratik     s2     700    IT
2   Sneha     s3     600  comp
3   Mayur     s4     500  Mech

In [80]:
#  column projection
df["name"]

0    Gaurav
1    Pratik
2     Sneha
3     Mayur
Name: name, dtype: object

In [81]:
df[["name","salary"]]




name  salary
0  Gaurav    1000
1  Pratik     700
2   Sneha     600
3   Mayur     500

In [82]:
# # row selection using index labels 
df.iloc[0]

name      Gaurav
rollno        s1
salary      1000
dept        comp
Name: 0, dtype: object

In [83]:
df.iloc[[0,1]]


name rollno  salary  dept
0  Gaurav     s1    1000  comp
1  Pratik     s2     700    IT

In [84]:
df= df.set_index('rollno')
df

name  salary  dept
rollno                      
s1      Gaurav    1000  comp
s2      Pratik     700    IT
s3       Sneha     600  comp
s4       Mayur     500  Mech

In [85]:
df.loc['s1']

name      Gaurav
salary      1000
dept        comp
Name: s1, dtype: object

In [86]:
df.loc[['s1','s2']]

name  salary  dept
rollno                      
s1      Gaurav    1000  comp
s2      Pratik     700    IT

In [87]:
df.loc['s1':'s3']


name  salary  dept
rollno                      
s1      Gaurav    1000  comp
s2      Pratik     700    IT
s3       Sneha     600  comp

In [88]:
# row selection using a filter / where clause / filtering the dataset
boolean_list = df['salary'] >599 # [True,True,True,False]
df[boolean_list]

name  salary  dept
rollno                      
s1      Gaurav    1000  comp
s2      Pratik     700    IT
s3       Sneha     600  comp

In [89]:
df.query('salary>599')

name  salary  dept
rollno                      
s1      Gaurav    1000  comp
s2      Pratik     700    IT
s3       Sneha     600  comp

In [90]:
df.query('salary>599')["name"]

rollno
s1    Gaurav
s2    Pratik
s3     Sneha
Name: name, dtype: object

In [91]:
# row selection using a filter / where clause / filtering the dataset
boolean_list = df['salary'] >599 # [True,True,True,False]
df[boolean_list]["name"]

rollno
s1    Gaurav
s2    Pratik
s3     Sneha
Name: name, dtype: object

In [92]:
# row selection using a filter / where clause / filtering the dataset 
# and also column projection 
df.loc[df['salary'] >599,"name"]

rollno
s1    Gaurav
s2    Pratik
s3     Sneha
Name: name, dtype: object

In [93]:
boolean_list = df['dept'].isin(["comp","IT"])
df.loc[boolean_list,'name']

rollno
s1    Gaurav
s2    Pratik
s3     Sneha
Name: name, dtype: object

In [94]:
df.query('dept in ("comp","IT")')['name']

rollno
s1    Gaurav
s2    Pratik
s3     Sneha
Name: name, dtype: object

In [95]:
df['salary'] = df['salary']*.10 + df['salary']
df

name  salary  dept
rollno                      
s1      Gaurav  1100.0  comp
s2      Pratik   770.0    IT
s3       Sneha   660.0  comp
s4       Mayur   550.0  Mech

In [96]:
def get_category(row):
    if  row['salary']> 999 :
        return "Overpaid"
    else:
        return "Underpaid" 
        
df['new_category'] = df.apply(get_category, axis = 1 )

df

name  salary  dept new_category
rollno                                   
s1      Gaurav  1100.0  comp     Overpaid
s2      Pratik   770.0    IT    Underpaid
s3       Sneha   660.0  comp    Underpaid
s4       Mayur   550.0  Mech    Underpaid

In [97]:
import re 
def get_sum(column):
        if column.dtype == type(1.1):
            sum = 0.0 
        else:   
            sum = ''
             
        for i in column.array:
            sum+=i
        return sum

# get_sum(pd.Series([1,2,3]))

df.apply(get_sum,axis = 0 )

name                         GauravPratikSnehaMayur
salary                                       3080.0
dept                                 compITcompMech
new_category    OverpaidUnderpaidUnderpaidUnderpaid
dtype: object